trigger: 
- master
pool:
  sc portal qa-and-up

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: opcgg015900011
    sourceFolder: 'templates'
    contents: 'SampleWebApp.war'
    targetFolder: '/home/vadmin/'
    readyTimeout: '80000'